language: python

matrix:
  include:
    # airflow supports Python 2.7 and 3.5
    - python: 2.7
      install: pip install -r requirements-dev.txt
      script:
        - tests/test.sh

    - python: 3.5
      install: pip install -r requirements-dev.txt
      script:
        - tests/test.sh

    # black doesn't run on old Python versions
    - python: 3.7
      install: pip install -r requirements-lint.txt
      script:
        - tests/lint.sh
